name: Build Alchemy APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Alchemy
        uses: actions/checkout@v4

      # FIX: Manually clone the missing dependency that the project expects locally
      - name: Clone Missing Dependencies
        run: |
          git clone https://github.com/aloisdeniel/figma_squircle figma_squircle

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run Code Generation
        # Required for Hive and the internal Alchemy database
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Alchemy-Install-File
          path: build/app/outputs/flutter-apk/app-release.apk
          
